Sprint 1
KosilovaDaria/middle.messenger.praktikum.yandex pull request #1
Opened 2022-07-26 15:00 UTC by KosilovaDaria

Здравствуйте! Отправляю свою работу на Ваш суд :)

2022-07-26 17:37 UTC, ivan-infro requested changes

2022-07-26 17:37 UTC, ivan-infro commented on .gitignore
> +.dist
Папка dist (без точки) должна быть в .gitignore
Не забудьте сначала (отдельным коммитом) закоммитить ее удаление

2022-07-26 17:37 UTC, ivan-infro commented on src/components/button/tpl.hbs
> +	<a href="{{path}}">{{label}}</a>
Тег a (anchor) нельзя использоваться внутри button
Обратите внимание, что кнопка "Зарегистрироваться" получилась кликабельной только в районе текста (тега <a>)
Есть и другие проблемы с <a> внтури <button>

2022-07-26 17:37 UTC, ivan-infro commented on src/modules/profile/index.js
> +		avatar: avatarprofile('file', 'file', 'file'),
Аватар кликабелен на странице смены пароля, так быть не должно

2022-07-26 17:37 UTC, ivan-infro commented on src/modules/chatDialog/tpl.hbs
> +  <button class="{{btnClass}}"><img src="{{img}}"></button>
<img width="249" alt="image" src="https://user-images.githubusercontent.com/5419627/181073159-dab73c3f-899f-4fc3-a382-60fc88f9b8db.png">

2022-07-26 17:37 UTC, ivan-infro commented on src/layout/chat/tpl.hbs
> +      {{{chatList}}}
Между элементами <li> не должно быть запятых
<img width="318" alt="image" src="https://user-images.githubusercontent.com/5419627/181073461-91e8b4d2-5a42-4309-a532-b36248bf39f4.png">

2022-07-27 09:54 UTC, KosilovaDaria commented on .gitignore
> +.dist
Сделала

2022-07-27 09:58 UTC, KosilovaDaria commented on src/components/button/tpl.hbs
> +	<a href="{{path}}">{{label}}</a>
Убрала из компонента кнопки ссылки. Где кнопка относится к форме - повесила пока на форму action (с cсылкой на страницу), кнопки для выхода из профиля пока сделала ссылками (когда буду настраивать роутинг то сделаю кнопки и повешу обработчики)

2022-07-27 09:58 UTC, KosilovaDaria commented on src/modules/profile/index.js
> +		avatar: avatarprofile('file', 'file', 'file'),
Задисейблила аватар  на странице профиля и странице смены пароля

2022-07-27 09:58 UTC, KosilovaDaria commented on src/modules/chatDialog/tpl.hbs
> +  <button class="{{btnClass}}"><img src="{{img}}"></button>
Поправила

2022-07-27 09:59 UTC, KosilovaDaria commented on src/layout/chat/tpl.hbs
> +      {{{chatList}}}
Пока поправила с использованием join(' '), когда буду обрабатывать данные от апи использую встроенный функционал шаблонизатора (#each)

2022-08-03 07:35 UTC, merged