Sprint 3
KosilovaDaria/middle.messenger.praktikum.yandex pull request #3
Opened 2022-10-06 09:52 UTC by KosilovaDaria

Добрый день!
Отправляю вам на проверку работу третьего спринта:
- реализовала роутер для перехода между страницами, 
- написала апи и контроллеры для получения данных (доступна регистрация нового пользователя, авторизация, выход, обновление данных пользователя и аватара, создание нового чата, добавление пользователя и удаление чата)
- подключила вебсокет, сообщения отправляются в реальном времени.
Подгрузка аватара для чата и отправка изображений в чате пока не реализованы.

2022-10-08 04:03 UTC, agadoev requested changes
Привет, @KosilovaDaria 
Спасибо за работу, я все внимательно посмотрел. Работа хорошая, но есть нюансы. Некоторые из них совсем простые, некоторые посложнее. Я попрошу тебя точно поправить несколько вещей:
1. Типизировать Store. Это важно, посколько Store - одна из важнейших частей всего SPA. Когда я читаю/пишу в Store. я хочу быть уверен, что не ошибусь с типами. Для этого и нужен TS, чтобы предупреждать нас об ошибках на этапе написания кода.
2. Разобраться с асинхронностью. Где-то забыт try/catch, где-то используются .then, а где-то await. И тот, и другой подход - окей, однако важно, чтобы соблюдался целостный стиль. Если не соблюдать единый стиль, то код быстро станет трудно поддерживаемым. Я попрошу тебя сделать либо через async await, либо через .then

В целом это все, давай поправим эти моменты и двинемся дальше :)

2022-10-08 04:03 UTC, agadoev commented on src/api/ChatApi.ts
> +    time: string;
Подумай над тем, чтобы использовать для обработки времени тип Date. Если нужно вывести время в виде отформатированной строки, удобно будет написать функцию, например
```
const formattedTime = (time: Date): string => { /* some logic */ }
```

2022-10-08 04:03 UTC, agadoev commented on src/api/ChatApi.ts
> +  users: [number],
Если в этом свойстве будут храниться id пользователей, то стоит переименовать свойство в usersIds. Иначе я ожидаю, что в массиве будут объекты типа User

2022-10-08 04:03 UTC, agadoev commented on src/components/avatar/style.module.css
> +  background: #efefef;
Цвета по хорошему должны быть в переменных

2022-10-08 04:03 UTC, agadoev commented on src/components/button/Button.ts
> +  type? : string;
тут можно конкретизировать тип, используя union.
Сейчас мы можем положить туда любую строку и TS не выдаст ошибку, значит мы словим ее в рантайме. Если мы будем использовать union и случайно сделаем опечатку в строке, то получим предупреждение и отловим ошибку на этапе написания кода
```suggestion
  type? : 'submit' | 'button' | 'reset';
```

2022-10-08 04:03 UTC, agadoev commented on src/components/chatDialog/ChatDialog.ts
> +          console.log(messageFromInput)
отладочные console.log'и полезны при разработке, но в репозитории их лучше не держать. Они загрязняют консоль и будут отвлекать внимание твоих коллег и тебя в будущем

2022-10-08 04:03 UTC, agadoev commented on src/controllers/ChatController.ts
> +    this.fetchChats()
это асинхронный метод и он должен вызываться через await

2022-10-08 04:03 UTC, agadoev commented on src/controllers/MessageController.ts
> +    const wsTransport = new WSTransport(`wss://ya-praktikum.tech/ws/chats/${userId}/${id}/${token}`);
Такие константы как урлы лучше выносить в отдельный файл с настройками проекта. Можешь назвать его например ```config.js``` и импортировать урл из него

2022-10-08 04:03 UTC, agadoev commented on src/utils/Store.ts
> +  private state: any = {};
Если есть тип для state, я бы не использовал тут any, а использовал бы этот тип
```suggestion
  private state: State = {};
```

2022-10-08 04:03 UTC, agadoev commented on src/utils/WSTransport.ts
> +}
подумай над тем, чтобы использовать union вместо enum'a. Union не транспилируется в объект, как enum, и на не нужно дублировать код (сейчас для каждого элемента перечисления дублируется строка). Подробнее можно почитать [тут](https://stackoverflow.com/questions/40275832/typescript-has-unions-so-are-enums-redundant)

2022-10-08 04:03 UTC, agadoev commented on src/utils/Route.ts
> +    // }
Лучше не держать закомментированный код в репозитории. Он может вводить в заблуждение. Комментарии могут быть полезными, а могут быть вредными. Если комментарий отвечает на вопрос "почему?", он полезный, в иных случаях - вредный

2022-10-08 04:03 UTC, agadoev commented on src/controllers/AuthController.ts
> +    const user = await this.api.read();
Тут нужно добавить try catch

2022-10-08 04:03 UTC, agadoev commented on src/controllers/AuthController.ts
> +      console.error(e.message);
было бы круто не просто выводить в console ошибку, а сообщать пользователю, что что-то пошло не так. Для этого можно использовать [snackbar](https://mui.com/material-ui/react-snackbar/), ну или просто через ```alert```

2022-10-08 08:45 UTC, KosilovaDaria commented on src/api/ChatApi.ts
> +  users: [number],
Здесь решила оставить как есть (чтоб не запутаться самой), чтоб соответствовало апи, представленном на сваггере: при запросе на добавление пользователя в чат ожидается объект вида 
 {
  "users": [
    0
  ],
  "chatId": 0
}

2022-10-08 08:55 UTC, KosilovaDaria commented on src/components/button/Button.ts
> +  type? : string;
Сделала

2022-10-08 09:04 UTC, KosilovaDaria commented on src/controllers/MessageController.ts
> +    const wsTransport = new WSTransport(`wss://ya-praktikum.tech/ws/chats/${userId}/${id}/${token}`);
Сделала

2022-10-08 09:18 UTC, KosilovaDaria commented on src/utils/Route.ts
> +    // }
Сделала

2022-10-08 09:36 UTC, KosilovaDaria commented on src/controllers/AuthController.ts
> +    const user = await this.api.read();
Сделала

2022-10-08 09:37 UTC, KosilovaDaria commented on src/controllers/AuthController.ts
> +      console.error(e.message);
Сделала

2022-10-08 09:37 UTC, KosilovaDaria commented on src/controllers/ChatController.ts
> +    this.fetchChats()
Поправила

2022-10-08 09:38 UTC, KosilovaDaria commented on src/components/chatDialog/ChatDialog.ts
> +          console.log(messageFromInput)
Убрала везде

2022-10-08 12:34 UTC, KosilovaDaria commented on src/utils/Store.ts
> +  private state: any = {};
Поправила

2022-10-08 13:39 UTC, KosilovaDaria commented on src/utils/WSTransport.ts
> +}
Очень тщательно прочитала статью, но как не билась с юнионом так не получилось оживить код - все время падают ошибки. Пока оставила енам, но обязательно разберу этот момент. Спасибо за подсказку!

2022-10-08 13:39 UTC, KosilovaDaria commented on src/components/avatar/style.module.css
> +  background: #efefef;
Все цвета определила в переменные

2022-10-08 13:40 UTC, KosilovaDaria commented on src/api/ChatApi.ts
> +    time: string;
Классная идея! Обязательно этим займусь дальше, спасибо

2022-10-09 03:14 UTC, agadoev approved these changes
Привет, @KosilovaDaria 
Спасибо за правки, вижу, что почти все исправлено. Работа принимается, удачи в следующем спринте :)

2022-10-09 07:18 UTC, merged